name: RandomTeleport
version: ${project.version}
main: me.darkeyedragon.randomtp.RandomTeleport
api-version: 1.13
authors: [DarkEyeDragon]
softdepend:
  - Factions
  - WorldGuard
  - GriefPrevention
  - GriefDefender
description: Yeet a player to a random location, and hopefully they won't die in the process
permissions:
  rtp.teleport.*:
    description: give all teleport permissions
    children:
      rtp.teleport.self: true
      rtp.teleport.other: true
      rtp.teleport.bypass: true
      rtp.teleport.world: true
  rtp.*:
    description: give all rtp commands
    children:
      rtp.teleport.*: true
      rtp.teleportdelay.bypass: true
      rtp.eco.*: true
  rtp.eco.*:
    description: bypass all economy restrictions
    children:
      rtp.eco.bypass: true
  rtp.admin.*:
    description: give all admin commands
    children:
      rtp.admin.removeworld: true
      rtp.admin.addworld: true
      rtp.admin.resetcooldown: true
      rtp.admin.reload: true
      rtp.admin.setprice: true
  rtp.teleport.self:
    description: random teleport yourself
  rtp.teleport.other:
    description: random teleport others
  rtp.teleport.world:
    description: random teleport to any world that doesnt require extra permissions
  rtp.teleport.bypass:
    description: bypass the cooldown
  rtp.teleportdelay.bypass:
    description: bypass initial tp delay
  rtp.eco.bypass:
    description: bypass economy costs
  rtp.admin.removeworld:
    description: allow admins to remove worlds from the config
  rtp.admin.addworld:
    description: allow admins to add worlds to the config
  rtp.admin.resetcooldown:
    description: allow admins to reset the cooldown timer of players
  rtp.admin.reload:
    description: allow admins to reload the plugin configs and repopulate queues
  rtp.admin.setprice:
    description: allow admins to set the teleport costs